version: '3.8'

services: 
  web:
    image: library-app:1.0.0
    container_name: library_web
    ports:
      - "8000:5000"
    environment:
      - DOTNET_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=library_db;Port=5432;Database=postgres;Username=postgres;Password=mysecretpassword
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - library-network


  postgres:
    image: postgres:latest
    container_name: library_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
volumes:
  postgres_data: 